# Generated by Django 4.0.4 on 2022-05-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
