# Generated by Django 4.0.4 on 2022-05-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review_reviewer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='product',
        ),
    ]
