# Generated by Django 4.0.4 on 2022-05-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_product_id_cart_product_cart_color_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
    ]
