# Generated by Django 4.0.4 on 2022-06-01 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='picture',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
