# Generated by Django 4.0.4 on 2022-06-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
