# Generated by Django 4.0.4 on 2022-06-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_solditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditems',
            name='size',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
