# Generated by Django 4.0.4 on 2022-06-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_solditems_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
