# Generated by Django 4.0.4 on 2022-07-11 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sales_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditems',
            name='date_sold',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 11, 15, 46, 44, 476685, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
