# Generated by Django 4.0.4 on 2022-05-01 16:05

import StoreProject.common.validators
import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(5), StoreProject.common.validators.validate_only_letters_and_numbers])),
                ('description', models.TextField()),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('in_stock', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Sweater', 'Sweater'), ('Jacket', 'Jacket'), ('Jeans', 'Jeans'), ('Dress', 'Dress'), ('Suit', 'Suit'), ('Hoodie', 'Hoodie'), ('Coat', 'Coat')], default='Shirt', max_length=7)),
            ],
        ),
    ]
