# Generated by Django 4.0.4 on 2022-05-02 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_name_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
