# Generated by Django 4.0.4 on 2022-05-09 12:22

import StoreProject.common.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_actual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[StoreProject.common.validators.validate_image_resolution]),
        ),
    ]
