# Generated by Django 4.0.4 on 2022-05-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
